# Generated by Django 3.1.2 on 2021-03-30 09:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everecon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
