# Generated by Django 3.1.2 on 2021-04-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0002_community_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/community/logos/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='members_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.DeleteModel(
            name='CommunityLeader',
        ),
    ]
