# Generated by Django 3.1.2 on 2021-04-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0004_community_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='creator',
            new_name='leader',
        ),
    ]
