# Generated by Django 3.1.2 on 2021-04-03 06:46

from django.db import migrations, models
import everecon.models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0005_auto_20210402_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='discord',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_discord]),
        ),
        migrations.AlterField(
            model_name='community',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_facebook]),
        ),
        migrations.AlterField(
            model_name='community',
            name='featured_video',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_youtube]),
        ),
        migrations.AlterField(
            model_name='community',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_instagram]),
        ),
        migrations.AlterField(
            model_name='community',
            name='linkedin',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_linkedin]),
        ),
        migrations.AlterField(
            model_name='community',
            name='twitter',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_twitter]),
        ),
    ]
