# Generated by Django 3.1.2 on 2021-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0008_auto_20210404_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='kind',
        ),
        migrations.AlterField(
            model_name='event',
            name='max_RSVP',
            field=models.IntegerField(default=300),
        ),
    ]
