# Generated by Django 3.1.2 on 2021-04-04 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0009_auto_20210404_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='events',
        ),
        migrations.AddField(
            model_name='event',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='everecon.community'),
            preserve_default=False,
        ),
    ]
