# Generated by Django 3.1.2 on 2021-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0010_auto_20210404_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='events', to='everecon.Tag'),
        ),
    ]
