# Generated by Django 3.1.2 on 2021-04-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0011_auto_20210408_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
