# Generated by Django 3.1.2 on 2021-04-21 07:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('everecon', '0013_auto_20210414_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='checkins',
            field=models.ManyToManyField(blank=True, related_name='events_checkedin', to=settings.AUTH_USER_MODEL),
        ),
    ]
