# Generated by Django 3.1.2 on 2021-04-21 11:33

import everecon.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0014_event_checkins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=everecon.models.path_and_rename_communitylogo),
        ),
        migrations.AlterField(
            model_name='community',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=everecon.models.path_and_rename_communitybanner),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=everecon.models.path_and_rename_event),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=everecon.models.path_and_rename_profile),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=everecon.models.path_and_rename_profile),
        ),
    ]
