# Generated by Django 3.1.2 on 2021-04-28 07:29

from django.db import migrations, models
import everecon.models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0015_auto_20210421_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[everecon.models.validation_mobile]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='facebook',
            field=models.URLField(validators=[everecon.models.validation_facebook]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='instagram',
            field=models.URLField(validators=[everecon.models.validation_instagram]),
        ),
    ]
