# Generated by Django 3.1.2 on 2021-05-04 09:07

from django.db import migrations, models
import everecon.models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0016_auto_20210428_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='facebook',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_facebook]),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='instagram',
            field=models.URLField(blank=True, null=True, validators=[everecon.models.validation_instagram]),
        ),
    ]
