# Generated by Django 3.1.2 on 2021-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('everecon', '0017_auto_20210504_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
